---
title: "eclipsaR_shiny"
format: html
server: shiny

execute:
  warning: false
---

```{r}
library(rmarkdown)
library(readr)
library(shiny)
library(plotly)
library(bslib)
```

```{r}
#| context: data
eclipses <- read_csv(
  "https://raw.githubusercontent.com/ma-ulloa/eclipsaR/main/data/formatted_eclipses.csv"
)

eclipses$Date <- as.Date(eclipses$Date)
eclipses$Year <- format(eclipses$Date, "%Y")
years <- sort(unique(eclipses$Year))

source("R/plot_magnitude.R")
source("R/plot_path.R")
```


```{r}
#| context: server
shinyApp(
  ui = page_fillable(
    layout_columns(
      col_widths = c(6, 6),
      card(
        card_header("Select an eclipse"),
        selectInput(
          "year_input",
          label = "Select year",
          choices = years,
          selected = "2017"
        ),
        selectInput("eclipse_input", label = "Select eclipse", choices = NULL)
      ),
      card(
        card_header("Sun view"),
        plotOutput("eclipse_sun", width = "500px", height = "500px")
      )
    ),
    layout_columns(
      col_widths = 12,
      card(
        card_header("Eclipse path"),
        plotlyOutput("eclipse_map", width = "500px", height = "500px")
      )
    )
  ),

  server = function(input, output, session) {
    # year (static)
    updateSelectInput(session, "year_input", choices = sort(years))

    # eclipses that happened in the selected year
    year_rows <- reactive({
      req(input$year_input)
      eclipses[eclipses$Year == as.integer(input$year_input), ]
    })

    observe({
      df <- year_rows()
      labels <- paste0(format(df$Date, "%Y-%m-%d"), " (", df$Type, ")")
      choices <- setNames(format(df$Date, "%Y-%m-%d"), labels)
      updateSelectInput(
        session,
        "eclipse_input",
        label = "Select eclipse",
        choices = choices
      )
    })

    # eclipse the user picked
    selected_row <- reactive({
      req(input$eclipse_input)
      match <- format(year_rows()$Date, "%Y-%m-%d") == input$eclipse_input
      req(any(match)) # <- this actually guards against zero matches
      year_rows()[match, ]
    })

    # --- "consequent actions" go here --------
    output$detail_output <- renderTable({
      req(selected_row())
      selected_row()[, c("Type", "Gamma", "Magnitude", "Latitude", "Longitude")]
    })

    output$eclipse_sun <- renderPlot({
      req(selected_row())

      # Extract data
      mag <- as.numeric(selected_row()$Magnitude)
      tp <- (selected_row()$Type)

      plot_magnitude(mag, tp)
    })

    output$eclipse_map <- renderPlotly({
      req(selected_row())

      # Extract data
      tp <- (selected_row()$Type)
      dt <- as.character(selected_row()$Date)
      url <- construct_url(dt, tp)

      plot_path(url)
    })
  },
  options = list(height = 600)
)
```